services:
    db:
        image: mysql:8
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: plant
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql

    app:
        build:
            context: .
        volumes:
            - .:/var/www
        depends_on:
            - db
        expose:
            - 9000
        environment:
            APP_ENV: "local"
            APP_DEBUG: "true"
            DB_CONNECTION: "mysql"
            DB_HOST: "db"
            DB_PORT: "3306"
            DB_DATABASE: "plant"
            DB_USERNAME: "laravel"
            DB_PASSWORD: "secret"
            CACHE_DRIVER: "file"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:8000/api/health" ]
            interval: 10s
            timeout: 5s
            retries: 10

volumes:
    dbdata:
