services:
    app:
        build:
            context: .
        container_name: plant-laravel
        ports:
            - "8000:8000"
        volumes:
            - .:/var/www
        depends_on:
            - db
        environment:
            APP_ENV: "local"
            APP_DEBUG: "true"
            APP_KEY: "base64:PLACEHOLDER"
            DB_CONNECTION: "mysql"
            DB_HOST: "db"
            DB_PORT: "3306"
            DB_DATABASE: "plant"
            DB_USERNAME: "laravel"
            DB_PASSWORD: "secret"
        command: >
            sh -c "
              php artisan config:clear &&
              php artisan migrate:fresh --seed &&
              php artisan serve --host=0.0.0.0 --port=8000
            "

    db:
        image: mysql:8
        container_name: mysql-plant
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: plant
            MYSQL_USER: laravel
            MYSQL_PASSWORD: secret
        volumes:
            - dbdata:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root

volumes:
    dbdata:
